language: php
php:
- 7.2
env:
  global:
    # - APP_HOST="iubar.it"
before_script:
  - cat /etc/os-release
  - php -v
script:
  - composer install --no-progress --no-interaction
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpstan -V
  - vendor/bin/phpstan analyse src --no-interaction --no-progress --level 0
  - vendor/bin/phpstan analyse src --no-interaction --no-progress --level max || true
  - phpunit
  - vendor/bin/var-dump-check --exclude vendor . || true
  - vendor/bin/psalm --version
  - vendor/bin/psalm || true
#  - vendor/bin/psalm --long-progress || true
  - vendor/bin/psalm --taint-analysis || true # https://psalm.dev/docs/security_analysis/
  - vendor/bin/psalm --set-baseline=psalm-baseline.xml || true # https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#using-a-baseline-file
  - vendor/bin/psalm --shepherd || true
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
    on_success: change  # options: [always|never|change] default: changes
    on_failure: always  # options: [always|never|change] default: always

    
