language: php
php:
- 5.5
env:
  global:
    # - APP_HOST="iubar.it"
before_script:
  - composer install --prefer-source --no-interaction --dev    
script: phpunit
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
    on_success: change  # options: [always|never|change] default: changes
    on_failure: always  # options: [always|never|change] default: always

    
